name: "Tagged Release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: |
            - `resvg-0.*.0.tar.xz` is a sources archive with vendored Rust dependencies
            - `resvg-linux-aarch64-musl.tar.gz` contains the `resvg` binary for Linux aarch64 musl
            - `usvg-linux-aarch64-musl.tar.gz` contains the `usvg` binary for Linux aarch64 musl

            Check [CHANGELOG](https://github.com/linebender/resvg/blob/${{ github.ref }}/CHANGELOG.md).
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  release-linux-aarch64-musl:
    name: Release Linux (aarch64-musl)
    runs-on: ubuntu-latest
    needs: ["create-release"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build resvg
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: aarch64-unknown-linux-musl
          args: --release -p resvg

      - name: Build usvg
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: aarch64-unknown-linux-musl
          args: --release -p usvg

      - name: Collect
        working-directory: target/aarch64-unknown-linux-musl/release
        run: |
          tar czf resvg-linux-aarch64-musl.tar.gz resvg
          tar czf usvg-linux-aarch64-musl.tar.gz usvg
          mkdir ../../bin
          cp resvg-linux-aarch64-musl.tar.gz ../../bin/
          cp usvg-linux-aarch64-musl.tar.gz ../../bin/

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Make vendored archive
        run: |
          VERSION=${{ steps.get_version.outputs.version-without-v }}
          echo $VERSION
          git clone https://github.com/linebender/resvg resvg-$VERSION
          cd resvg-"$VERSION"
          mkdir -p .cargo
          cargo vendor > .cargo/config
          cd ..
          env XZ_OPT="-9e" tar \
              --exclude=".git" \
              --exclude="resvg-$VERSION/.github" \
              --exclude="resvg-$VERSION/version-bump.md" \
              --exclude="resvg-$VERSION/docs" \
              -cJf resvg-"$VERSION".tar.xz resvg-"$VERSION"
            mkdir -p bin
          cp resvg-"$VERSION".tar.xz bin/

      - name: Upload binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["bin/*"]'
